# VDJServer Docker Orchestration


vdjnginx:
    build: vdjserver-nginx
    ports:
        - "8080:80"
    volumes_from:
        - vdjbackbone
    volumes:
        - /etc/pki/:/etc/pki/:ro
    env_file: vdjserver-nginx/.env
    #command: /bin/bash /root/nginx-config-replace.sh
    #volumes:
    #    - logs/apache:/var/log/apache2
    #    - logs/cakephp/error.log:/var/www/html/xsede-api-core/app/tmp/logs/error.log

vdjauth:
    build: vdjserver-auth

vdjbackbone:
    build: vdjserver-backbone
    #command: build && tail -f /var/www/html/vdjserver/backbone/package.json #cd /var/www/html/vdjserver-backbone && /usr/local/bin/grunt --gruntfile /vdjserver-backbone/Gruntfile.js build
