# VDJServer Docker Orchestration

nginx:
    build: vdjserver-web-nginx
    env_file: .env
    links:
        - vdjapi
    log_driver: "syslog"
    ports:
        - "80:80"
        - "443:443"
    volumes_from:
        - vdjbackbone
    volumes:
        - /etc/pki/:/etc/pki/:ro

redis:
    build: vdjserver-web-redis
    expose:
        - "6379"
    log_driver: "syslog"
    volumes:
        - vdjserver-web-redis/data:/data

vdjapi:
    build: vdjserver-web-api
    env_file: .env
    expose:
        - "8443"
    links:
        - redis
    log_driver: "syslog"
    volumes:
        - /etc/pki/:/etc/pki/:ro

vdjbackbone:
    build: vdjserver-web-backbone
    log_driver: "syslog"
