# VDJServer Docker Orchestration

nginx:
    build: vdjserver-web-nginx
    links:
        - vdjapi
    log_driver: "syslog"
    ports:
        - "8080:8080"
    volumes_from:
        - vdjbackbone
        - vdjml

vdjapi:
    build: vdjserver-web-api
    env_file: ./vdjserver-web-api/.env
    expose:
        - "8081"
    log_driver: "syslog"
    volumes:
        - ./vdjserver-web-api/redis:/vdjserver-web-api/redis

vdjbackbone:
    build: vdjserver-web-backbone
    log_driver: "syslog"

vdjml:
    build: vdjml
    log_driver: "syslog"
