# VDJServer Docker Orchestration

vdjnginx:
    build: vdjserver-web-nginx
    env_file: .env
    links:
        - vdjapi
    ports:
        - "80:80"
        - "443:443"
    volumes_from:
        - vdjbackbone
    volumes:
        - /etc/pki/:/etc/pki/:ro
        - /var/log/vdjserver-web/vdjserver-web-nginx/:/var/log/nginx/persistent/

vdjapi:
    build: vdjserver-web-api
    env_file: .env
    expose:
        - "8443"
    volumes:
        - /etc/pki/:/etc/pki/:ro
        - /var/log/vdjserver-web/vdjserver-web-api:/vdjserver-web-api/logs

vdjbackbone:
    build: vdjserver-web-backbone
