# VDJServer Docker Orchestration

version: '2'

services:
    vdj-nginx:
        build: ./../../vdjserver-web-nginx
        container_name: vdj-nginx
        image: vdjserver/vdj-nginx:v2-develop
        depends_on:
            - vdj-api
            - vdj-backbone
#            - vdj-doc
        networks:
            - default
        ports:
            - "8080:8080"
        volumes_from:
            - vdj-backbone
#            - vdj-doc

    vdj-api:
        build: ./../../vdjserver-web-api
        container_name: vdj-api
        env_file: ./../../vdjserver-web-api/.env
        expose:
            - "8081"
        image: vdjserver/vdj-api:v2-develop
        networks:
            - default
        volumes:
            - ./../../vdjserver-web-api/redis:/vdjserver-web-api/redis

    vdj-backbone:
        build: ./../../vdjserver-web-backbone
        container_name: vdj-backbone
        image: vdjserver/vdj-backbone:v2-develop
        volumes:
            - ./../../vdjserver-web-backbone/docker/environment-config/v2:/var/www/html/vdjserver-v2-web-backbone/app/scripts/config/

#    vdj-doc:
#        container_name: vdj-doc
#        image: vdjserver/doc

networks:
    default:
        driver: bridge
