#!/bin/bash
#
### BEGIN INIT INFO
# Provides: vdjserverweb
# Defalt-Start: 3 4 5
# Default-Stop: 0 1 6
# Description: VDJServer Web Infrastructure init script
### END INIT INFO

COMPOSE=/usr/bin/docker-compose
WORKING_DIR="/var/www/docker/vdjserver-web"

start_compose() {
    cd $WORKING_DIR && $COMPOSE up -d
}

stop_compose() {
    cd $WORKING_DIR && $COMPOSE stop
}

remove_compose() {
    cd $WORKING_DIR && $COMPOSE rm --force
}

build_compose() {
    cd $WORKING_DIR && $COMPOSE build
}

clean_build_compose() {
    cd $WORKING_DIR && $COMPOSE build --no-cache
}

case "$1" in
  start)
    echo "Starting VDJServer Web Infrastructure..."
    start_compose
    ;;

  stop)
    echo "Stopping VDJServer Web Infrastructure..."
    stop_compose
    ;;

  restart)
    echo "Restarting VDJServer Web Infrastructure..."
    stop_compose
    start_compose
    ;;

  rebuild)
    echo "Rebuilding VDJServer Web Infrastructure..."
    build_compose
    stop_compose
    remove_compose
    start_compose
    ;;

  rebuild-without-cache)
    echo "Rebuilding VDJServer Web Infrastructure without using cached data..."
    clean_build_compose
    stop_compose
    remove_compose
    start_compose
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|rebuild|rebuild-without-cache}"
    exit 1
esac

exit 0
