# VDJServer Docker Orchestration

version: '2'

services:
    vdj-nginx:
        build: ./../../vdjserver-web-nginx
        container_name: vdjtest-nginx-agave-staging
        image: vdj-nginx:agave-staging
        networks:
            - default
        ports:
            - "8100:8080"
        volumes_from:
            - vdj-backbone
            - vdjml

    vdj-api:
        build: ./../../vdjserver-web-api
        container_name: vdjtest-api-agave-staging
        env_file: ./../../vdjserver-web-api/.test-env
        expose:
            - "8081"
        image: vdj-api:agave-staging
        networks:
            - default
        volumes:
            - ./../../vdjserver-web-api/redis:/vdjserver-web-api/redis

    vdj-backbone:
        build: ./../../vdjserver-web-backbone
        container_name: vdjtest-backbone-agave-staging
        image: vdj-backbone:agave-staging
        volumes:
            - ./../../vdjserver-web-backbone/docker/environment-config/test:/var/www/html/vdjserver-backbone/dist/scripts/config/

    vdj-backbone-test:
        command: grunt test
        container_name: vdjtest-backbone-test-agave-staging
        depends_on:
            - vdj-backbone
        image: vdj-backbone:agave-staging
        networks:
            - default
        ports:
            - "8102:9002"
        volumes:
            - ./../../vdjserver-web-backbone/docker/environment-config/test:/var/www/html/vdjserver-backbone/app/scripts/config/
        working_dir: /var/www/html/vdjserver-backbone

    vdjml:
        container_name: vdjml-test-agave-staging
        image: vdjserver/vdjml

networks:
    default:
        driver: bridge
