# VDJServer Docker Orchestration

version: '2'

services:
    vdj-nginx:
        logging:
            driver: "syslog"

    vdj-api:
        logging:
            driver: "syslog"

    vdj-backbone:
        logging:
            driver: "syslog"

    vdj-doc:
        logging:
            driver: "syslog"
