# VDJServer Docker Orchestration

version: '2'

services:
    vdj-nginx:
        build: ./../../vdjserver-web-nginx
        container_name: vdj-nginx
        image: vdj-nginx
        depends_on:
            - vdj-api
            - vdj-backbone
            - vdj-doc
        networks:
            - default
        ports:
            - "8080:8080"
        volumes_from:
            - vdj-backbone
            - vdj-doc

    vdj-api:
        build: ./../../vdjserver-web-api
        container_name: vdj-api
        env_file: ./../../vdjserver-web-api/.env
        expose:
            - "8081"
        image: vdj-api
        networks:
            - default
        volumes:
            - ./../../vdjserver-web-api/redis:/vdjserver-web-api/redis

    vdj-backbone:
        build: ./../../vdjserver-web-backbone
        container_name: vdj-backbone
        image: vdj-backbone
        volumes:
            - ./../../vdjserver-web-backbone/docker/environment-config/run:/var/www/html/vdjserver-backbone/dist/scripts/config/

    vdj-doc:
        container_name: vdj-doc
        image: vdjserver/doc

networks:
    default:
        driver: bridge
