# VDJServer Docker Orchestration

version: '2'

services:
    vdj-nginx:
        build: ./../../vdjserver-web-nginx
        container_name: vdj-nginx
        image: vdj-nginx
        networks:
            - default
        ports:
            - "8080:8080"
            - "8090:8090"
        volumes_from:
            - vdj-backbone
            - vdjml

    vdj-api:
        build: ./../../vdjserver-web-api
        container_name: vdj-api
        env_file: ./../../vdjserver-web-api/.env-test
        expose:
            - "8081"
        image: vdj-api
        networks:
            - default
        volumes:
            - ./../../vdjserver-web-api/redis:/vdjserver-web-api/redis

    vdj-backbone:
        build: ./../../vdjserver-web-backbone
        container_name: vdj-backbone
        image: vdj-backbone
        volumes:
            - ./../../vdjserver-web-backbone/docker/environment-config/test:/var/www/html/vdjserver-backbone/dist/scripts/config/

    vdj-backbone-test:
        command: grunt --gruntfile /var/www/html/vdjserver-backbone/Gruntfile.js test
        container_name: vdj-backbone-test
        depends_on:
            - vdj-backbone
        image: vdj-backbone
        volumes:
            - ./../../vdjserver-web-backbone/docker/environment-config/test:/var/www/html/vdjserver-backbone/dist/scripts/config/

    vdjml:
        container_name: vdjml
        image: vdjserver/vdjml

networks:
    default:
        driver: bridge
